name: ex_engse608
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.10.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  sqflite: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true